# -*- mode: ruby -*-
# vi: set ft=ruby :

#$script = <<-SCRIPT
#echo "I like Vagrant"
#echo "I love Linux"
#SCRIPT

Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  
  config.vm.boot_timeout = 600
  
  config.vm.provision :docker
  #config.vm.provision :shell, path: "bootstrap.sh"
  #config.vm.provision :file, source: "file.txt", destination: "file.txt"
  #config.vm.provision :file, source: "dir1", destination: "dir1"
  config.vm.provision :file, source: "docker-compose.yaml", destination: "docker-compose.yaml"

  config.vm.define "server-1" do |dockerserver|
    dockerserver.vm.network "private_network", ip: '192.168.56.10'
    dockerserver.vm.hostname = "dockerserver"
    #dockerserver.vm.provision "shell", inline: "echo Hi Class!"
    #dockerserver.vm.provision "shell", inline:  $script
    #dockerserver.vm.provision "shell" do |s|
    #  s.inline = "echo $1"
    #  s.args = ["AT", "Class!"]
    #end
    dockerserver.vm.provision "docker_compose", yml: "/vagrant/docker-compose.yaml"   
  end
end
